name: deploy-pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests (headless)
        run: npm test -- --watch=false --browsers=ChromeHeadless || echo "No tests yet"

      - name: Build Angular (prod) con base-href per GitHub Pages
        run: |
          npm run build -- --configuration production --base-href /hello-devops-angular/

      - name: Trova cartella di output (dist)
        id: loc
        run: |
          if [ -f dist/hello/index.html ]; then
            echo "out=dist/hello" >> $GITHUB_OUTPUT
          elif [ -f dist/hello/browser/index.html ]; then
            echo "out=dist/hello/browser" >> $GITHUB_OUTPUT
          else
            echo "index.html non trovato in dist/hello o dist/hello/browser"
            echo "Contenuto dist:"
            ls -R dist || true
            exit 1
          fi

      - name: Aggiungi 404.html (SPA fallback)
        run: cp "${{ steps.loc.outputs.out }}/index.html" "${{ steps.loc.outputs.out }}/404.html"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.loc.outputs.out }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4